platform :ios do
  private_lane :build_prod do
    increment_version_number_in_plist(
      xcodeproj: "./ios/FadoWallet.xcodeproj",
      target: "FadoWallet",
    )

    increment_build_number(
      xcodeproj: "./ios/FadoWallet.xcodeproj"
    )

    update_app_identifier(
      xcodeproj: "./ios/FadoWallet.xcodeproj",
      plist_path: 'FadoWallet/Info.plist', # Path to info plist file, relative to xcodeproj
      app_identifier: "com.fadowallet.app" # The App Identifier
    )

    update_project_provisioning(
      xcodeproj: "./ios/FadoWallet.xcodeproj",
      profile: "./fastlane/FadoWalletProdProfile.mobileprovision",
      code_signing_identity: "iPhone Distribution: Pham Tan Dat (Z9BL6FV726)"
    )

    # Change the Display Name of your app
    update_info_plist( 
      xcodeproj: "./ios/FadoWallet.xcodeproj",
      plist_path: 'FadoWallet/Info.plist',
      display_name: "Fado Wallet",
    )

    # Build .ipa file
    gym(
      scheme: "FadoWallet",
      workspace: "./ios/FadoWallet.xcworkspace",
      export_method: "ad-hoc",
      output_directory:'./fastlane/build',
      output_name: "FadoWalletProd.ipa",
    )
  end

  lane :prod do
    build_prod

    APP_VERSION = get_version_number(
      xcodeproj: "./ios/FadoWallet.xcodeproj",
      target: "FadoWallet"
    )

    # Deploy to firebase app distribution to test
    firebase_app_distribution(
      app: "1:1097658756982:ios:17b7a72ddc6ff6a3621457",
      release_notes: "new ios prod test release #{APP_VERSION}",
      ipa_path: "./fastlane/build/FadoWalletProd.ipa",
      groups: "fado,ios",
    )

    # Commit release
    git_commit(
      path: "*",
      message: "new ios prod test release #{APP_VERSION}",
    )

    push_to_git_remote()
  end
end

platform :android do
  private_lane :build_prod do
    increment_version_code(
      gradle_file_path: './android/app/build.gradle'
    )

    # build .apk file
    build_android_app(
      project_dir: './android',
      task: "assemble",
      build_type: "Release",
    )

    # move .apk file to build folder
    APK_LOCATION = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
    sh("mv #{APK_LOCATION} ./build/FadoWalletProd.apk")
  end

  lane :prod do
    build_prod

    firebase_app_distribution(
      app: "1:1097658756982:android:31584eda47b373a4621457",
      release_notes: "new android prod test release",
      apk_path:'./fastlane/build/FadoWalletProd.apk',
      groups: 'fado,android',
    )

    # Commit release
    git_commit(
      path: "*",
      message: "new android prod test release",
    )

    push_to_git_remote()
  end
end 